tabletop_keywords = [
    "analog game",
    "analogici",
    "analogue game",
    "belonging outside belonging",
    "fitd",
    "gamebooks",
    "gmless",
    "megadungeon",
    "osr",
    "pamphlet",
    "pbta",
    "physical game",
    "srd",
    "sword dream",
    "sworddream",
    "system reference document",
    "tabletop",
    "table-top",
    "ttrpg",
    "zine",
]

digital_keywords = [
    "any engine",
    "bitsy jam",
    "game boy",
    "gimkit",
    "godot engine",
    "fps",
    "hyper game jam",
    "interactive fiction",
    "longterm tech innovation jams",
    "migjam",
    "ms-dos",
    "platformer",
    "playable build",
    "playable in the browser",
    "playable on computers",
    "python game jam",
    "rpg maker",
    "shmup",
    "sound design",
    "source code",
    "theana game jam", # repeating digital game jam
    "trijam",
    "unity",
    "unreal",
    "voxel art",
    "zgd game jam",
]
