tabletop_keywords = [
        "analog game",
        "analogici",
        "analogue game",
        "belonging outside belonging",
        "fitd",
        "gamebooks",
        "gmless",
        "megadungeon",
        "osr",
        "pamphlet",
        "pbta",
        "physical game",
        "srd",
        "sword dream",
        "sworddream",
        "system reference document",
        "tabletop",
        "ttrpg",
]

digital_keywords = [
    "any engine",
    "bitsy jam",
    "game boy",
    "fps",
    "hyper game jam",
    "ms-dos",
    "playable on computers",
    "python game jam",
    "rpg maker",
    "shmup",
    "source code",
    "trijam",
    "unity",
    "unreal",
    "zgd game jam",
]
